# Generated by Django 4.0.4 on 2022-09-19 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointToCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.DateTimeField(auto_now_add=True)),
                ('currency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='point', to='points.currency')),
            ],
        ),
    ]
