# Generated by Django 4.0.4 on 2022-09-16 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0002_organisation_facebook_organisation_instagram_and_more'),
        ('projects', '0003_project_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProjectOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationInProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organisations.organisation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisations', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'organisation')},
            },
        ),
    ]
