# Generated by Django 4.0.4 on 2022-09-19 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_addprojectorganisation_organisationinproject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddProjectOrganisation',
        ),
    ]
