# Generated by Django 4.0.4 on 2022-09-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_alter_tree_created_on_alter_tree_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='tree_type',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
