# Generated by Django 4.0.4 on 2022-09-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0003_tree_tree_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='planted_at',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
