# Generated by Django 4.0.4 on 2022-09-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0004_tree_planted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='planted_at',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
