# Generated by Django 4.0.4 on 2022-09-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0005_alter_tree_planted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='height',
            field=models.CharField(max_length=30),
        ),
    ]
