# Generated by Django 4.0.4 on 2022-09-11 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_institutioncategories_profile_institution_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='institutionofficial',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='institutionofficial',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='institutionofficial',
            name='user',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
        migrations.DeleteModel(
            name='InstitutionCategories',
        ),
        migrations.DeleteModel(
            name='InstitutionOfficial',
        ),
    ]
