# Generated by Django 4.0.4 on 2022-09-25 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trees', '0005_alter_tree_planted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('timing', models.CharField(choices=[('day', 'day'), ('night', 'night')], max_length=30)),
                ('temperature', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('windspeed', models.IntegerField()),
                ('weather', models.CharField(max_length=30)),
                ('uvIndex', models.IntegerField()),
                ('uvDescription', models.CharField(max_length=30)),
                ('narrative', models.TextField()),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_checks', to='trees.tree')),
            ],
        ),
    ]
