# Generated by Django 4.0.4 on 2022-09-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='facebook',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='instagram',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='phone_no',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='tiktok',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='twitter',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='year_founded',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
