# Generated by Django 4.0.4 on 2022-09-25 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintainance', '0002_alter_treemaintainance_height_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treemaintainance',
            options={'ordering': ['-pk']},
        ),
    ]
