# Generated by Django 4.0.4 on 2022-09-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintainance', '0003_alter_treemaintainance_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treemaintainance',
            name='height',
            field=models.CharField(max_length=40),
        ),
    ]
