# Generated by Django 4.0.4 on 2022-09-01 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFootPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=40)),
                ('home_emmission', models.DecimalField(decimal_places=2, max_digits=40)),
                ('travel_emmission', models.DecimalField(decimal_places=2, max_digits=40)),
                ('food_emmission', models.DecimalField(decimal_places=2, max_digits=40)),
                ('secondary_emmission', models.DecimalField(decimal_places=2, max_digits=40)),
                ('calculated_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footprints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
